name: Build on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  macos:
    strategy:
      matrix:
        os: [ macos-13, macos-latest ]
    uses: ./.github/workflows/_build-macos.yaml
    with:
      os: ${{ matrix.os }}
