name: Build on Tag

on:
  push:
    tags:
      - 'v*'
#    branches:
#      - main

jobs:
  macos:
    strategy:
      matrix:
        os: [ macos-13, macos-latest ]
    uses: ./.github/workflows/_build-macos.yaml
    with:
      os: ${{ matrix.os }}

  windows:
    uses: ./.github/workflows/_build-windows.yaml

  linux:
    uses: ./.github/workflows/_build-linux.yaml

  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs:
      - macos
      - windows
      - linux
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R release

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*
          generate_release_notes: true
